version: 2.1

jobs:
  unit_testing:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run:
          name: Unit testing
          command: lein test

workflows:
  version: 2
  unit_testing:
    jobs:
      - unit_testing
